const ProductCardData=[
    {productName:"Iphone 15 pro max",description:"The iPhone 15 Pro Max is the latest flagship smartphone from Apple, designed to offer an unparalleled user experience with cutting-edge technology and premium features. This device boasts a stunning 6.7-inch Super Retina XDR display, providing vibrant colors and sharp details for an immersive viewing experience. The ProMotion technology ensures smooth scrolling and responsiveness with a 120Hz refresh rate.",price:"2,00,000",id:"100"},
    {productName:"Samsung J7",description:"The Samsung Galaxy J7 is a mid-range Android smartphone that was released in 2015. It features a 5.5-inch HD Super AMOLED display, providing vibrant colors and sharp visuals. The device is powered by either a Qualcomm Snapdragon 615 or Exynos 7580 chipset, depending on the region, and comes with 1.5GB of RAM and 16GB of internal storage, which can be expanded via a microSD card1.",price:"15,000",id:"101"},
    {productName:"toy car",description:"I found some information related to toy cars in the context of Vodafone's activities. For example, there was a recent donation drive at VOIS India where employees contributed toys, including toy cars, to support communities in need1. Additionally, there was a mention of Vodafone saving Christmas by connecting a warehouse for Smyths Toys Superstores, which likely includes toy cars",price:"300",id:"102"},
    {productName:"wooden table",description:"Wooden tables are celebrated for their strength, durability, and timeless appeal. They come in various styles and finishes, making them a versatile choice for any home or office. Wooden dining tables, for instance, offer unparalleled durability and a unique ability to age gracefully, gaining character and warmth over time. They can be easily sanded and refinished, making them a practical choice for busy households4. Solid wood dining tables are also known for their strength and longevity, with the natural grain of the wood adding a unique character to each piece5.",price:"4,000",id:"103"},
    {productName:"Casual Tshirt",description:"A casual T-shirt is a versatile and comfortable piece of clothing that can be worn for various occasions. Made from soft, breathable fabric, it offers a relaxed fit and is perfect for everyday wear. Available in a range of colors and designs, a casual T-shirt can be easily paired with jeans, shorts, or skirts for a laid-back look.",price:"250",id:"104"},
    {productName:"Denim Jeans",description:"Denim jeans are a timeless wardrobe staple known for their durability and style. Made from high-quality denim fabric, these jeans offer a comfortable fit and come in various cuts, including skinny, straight, and bootcut. Whether dressed up with a blazer or dressed down with a T-shirt, denim jeans are perfect for any occasion.",price:"1,200",id:"105"},
    {productName:"Bracelet",description:"A bracelet is a stylish accessory that adds a touch of elegance to any outfit. Available in various materials such as gold, silver, leather, and beads, bracelets can be simple or adorned with charms and gemstones. They are perfect for both casual and formal occasions, making them a versatile addition to your jewelry collection.",price:"600",id:"106"},
    {productName:"Wooden Bed",description:"A wooden bed is a classic and sturdy piece of furniture that adds warmth and character to any bedroom. Crafted from high-quality wood, it offers durability and a timeless aesthetic. Wooden beds come in various styles, including traditional, modern, and rustic, and can be paired with different types of mattresses for a comfortable night's sleep.",price:"7,000",id:"107"},
    {productName:"Mobile Charger",description:"A mobile charger is an essential accessory for keeping your smartphone powered up throughout the day. Designed to be compact and portable, it allows you to charge your device quickly and efficiently. Mobile chargers come in various types, including wall chargers, car chargers, and wireless chargers, ensuring you stay connected wherever you go.",price:"1,500",id:"108"},
    {productName:"Mobile Cover",description:"A mobile cover is a protective accessory that helps safeguard your smartphone from scratches, drops, and other damage. Available in a wide range of materials, such as silicone, leather, and plastic, mobile covers also come in various designs and colors to suit your personal style. They provide both protection and a personalized look for your device",price:"430",id:"109"},
]

export default ProductCardData;